version: '3.4'

services:
  lastfmstats:
    build:
      context: .
      dockerfile: LastFmStatsServer/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - "./../settings.json:/settings/settings.json"
      - "./../data:/data"
