version: '3.4'

services:
  lastfmstats:
    ports:
      - "127.0.0.1:5000:80"
    environment:
      APP_SETTINGS_PATH: "/settings/settings.json"
    restart: unless-stopped
    volumes:
      - "./settings.json:/settings/settings.json"
      - "./data:/data"
